# ============================================================
# McDonald's HK Sales Dashboard - Synthetic Data Generator
# Run with: python3 generate_data.py
# Generated by Kiro CLI
# ============================================================

import random
from datetime import date, timedelta

random.seed(42)

hour_weights = {10:1,11:4,12:8,13:8,14:8,15:3,16:3,17:3,18:7,19:7,20:7,21:2,22:2,23:2}
day_weights = {'Monday':1.0,'Tuesday':1.0,'Wednesday':1.0,'Thursday':1.0,'Friday':1.3,'Saturday':1.4,'Sunday':1.35}
day_names = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

item_weights = {
    1:15,2:10,3:12,4:11,5:10,6:8,7:6,8:7,25:5,
    9:14,10:8,11:13,12:8,13:5,14:6,15:4,16:3,17:4,
    18:5,19:6,20:4,21:3,22:2,23:4,24:9
}
prices = {
    1:4.5,2:5.0,3:6.5,4:5.5,5:5.0,6:3.5,7:4.0,8:4.5,9:2.5,10:3.0,
    11:2.0,12:2.5,13:3.5,14:2.0,15:3.0,16:3.5,17:2.5,18:3.0,19:1.5,
    20:2.0,21:2.5,22:2.0,23:4.0,24:8.5,25:7.0
}

orders, order_items = [], []
oid, oiid = 0, 0
start = date(2023, 1, 1)

for day_offset in range(90):
    d = start + timedelta(days=day_offset)
    dow = day_names[d.weekday()]
    dw = day_weights[dow]
    month = d.month
    for h in range(10, 24):
        for _ in range(max(1, round(hour_weights[h] * dw * 0.95))):
            oid += 1
            orders.append((oid, str(d), h, dow))
            used = set()
            for _ in range(random.choices([1,2,3,4], weights=[15,45,30,10])[0]):
                w = dict(item_weights)
                if h > 11:
                    for bid in [15,16,17]: w[bid] = 0
                if month == 3:
                    w[18] *= 2; w[19] *= 3
                ids = list(w.keys())
                item_id = random.choices(ids, weights=[w[i] for i in ids])[0]
                if item_id in used: continue
                used.add(item_id)
                qty = random.choices([1,2], weights=[85,15])[0]
                oiid += 1
                order_items.append((oiid, oid, item_id, qty, round(prices[item_id]*qty, 2)))

def write_inserts(table, rows, cols, filename):
    with open(filename, 'w') as f:
        batch = []
        for i, r in enumerate(rows):
            vals = ','.join(f"'{v}'" if isinstance(v, str) else str(v) for v in r)
            batch.append(f"({vals})")
            if len(batch) == 500 or i == len(rows)-1:
                f.write(f"INSERT INTO mcdhk.{table} ({','.join(cols)}) VALUES {','.join(batch)};\n")
                batch = []

write_inserts('orders', orders, ['order_id','order_date','order_hour','order_day_of_week'], 'sql/02_orders_data.sql')
write_inserts('order_items', order_items, ['order_item_id','order_id','item_id','quantity','line_total'], 'sql/03_order_items_data.sql')

print(f"Generated {len(orders)} orders and {len(order_items)} order items")
print(f"Total revenue: HK${sum(oi[4] for oi in order_items):,.2f}")
print(f"SQL files written to sql/ directory")
