-- ============================================================
-- McDonald's HK Sales Dashboard - Redshift Datamart Setup
-- Generated by Kiro CLI
-- ============================================================

-- Step 1: Create dedicated schema
CREATE SCHEMA IF NOT EXISTS mcdhk;

-- Step 2: Create dimension tables
CREATE TABLE mcdhk.categories (
  category_id   INT PRIMARY KEY,
  category_name VARCHAR(50) NOT NULL
);

CREATE TABLE mcdhk.menu_items (
  item_id     INT PRIMARY KEY,
  item_name   VARCHAR(100) NOT NULL,
  category_id INT NOT NULL,
  unit_price  DECIMAL(10,2) NOT NULL
);

-- Step 3: Create fact tables
CREATE TABLE mcdhk.orders (
  order_id        INT PRIMARY KEY,
  order_date      DATE NOT NULL,
  order_hour      INT NOT NULL,
  order_day_of_week VARCHAR(10) NOT NULL
);

CREATE TABLE mcdhk.order_items (
  order_item_id INT PRIMARY KEY,
  order_id      INT NOT NULL,
  item_id       INT NOT NULL,
  quantity      INT NOT NULL,
  line_total    DECIMAL(10,2) NOT NULL
);

-- Step 4: Load dimension data
INSERT INTO mcdhk.categories VALUES
(1,'Burgers'),(2,'Chicken'),(3,'Fries'),(4,'Drinks'),
(5,'Breakfast'),(6,'Desserts'),(7,'Sides'),(8,'Wraps');

INSERT INTO mcdhk.menu_items VALUES
(1,'Big Mac',1,4.50),
(2,'Quarter Pounder with Cheese',1,5.00),
(3,'Angus Third Pounder',1,6.50),
(4,'Bulgogi Burger',1,5.50),
(5,'Meatball Marinara',1,5.00),
(6,'McChicken',2,3.50),
(7,'Spicy McNuggets 6pc',2,4.00),
(8,'Chicken McCrispy',2,4.50),
(9,'Fries Medium',3,2.50),
(10,'Fries Large',3,3.00),
(11,'Soft Drink Medium',4,2.00),
(12,'Soft Drink Large',4,2.50),
(13,'McCafe Latte',4,3.50),
(14,'Iced Tea',4,2.00),
(15,'Egg McMuffin',5,3.00),
(16,'Hotcakes',5,3.50),
(17,'Sausage McMuffin',5,2.50),
(18,'McFlurry',6,3.00),
(19,'Ice Cream Cone',6,1.50),
(20,'Apple Pie',6,2.00),
(21,'Side Salad',7,2.50),
(22,'Corn Cup',7,2.00),
(23,'Chicken Wrap',8,4.00),
(24,'Big Mac Combo',1,8.50),
(25,'McChicken Combo',2,7.00);
